[book]
authors = ["Luke Bailey"]
language = "en"
multilingual = false
src = "src"
title = "rp2040nix"
repository = "https://github.com/baileyluTCD/rp2040nix"
description = "A small, opinionated framework for building rp2040 apps with nix."

[output.html]
git-repository-url = "https://github.com/baileyluTCD/rp2040nix"
git-repository-icon = "fa-github"
